// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:packageId/:sourceMode": {
    params: {
      "packageId": string;
      "sourceMode": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/:packageId/:sourceMode";
  };
  "routes/index.jsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/package-validator.jsx": {
    id: "routes/package-validator";
    page: "/:packageId/:sourceMode";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/index": typeof import("./app/routes/index.jsx");
  "routes/package-validator": typeof import("./app/routes/package-validator.jsx");
};