export { CaptionStore } from './CaptionStore';
export {
    CaptionShapeSchema,
    PointSchema,
    RgbColorSchema,
    FillStyleSchema,
    StrokeStyleSchema,
    CaptionBackgroundStyleSchema,
    CaptionPointerConfigSchema,
    CaptionThoughtConfigSchema,
    CaptionConfigSchema,
    DEFAULT_CAPTION_TEXT_STYLE,
    DEFAULT_CAPTION_BACKGROUND_STYLE,
    rgbToNumber,
    mergeBackgroundStyle,
    resolveCaptionConfig,
    type CaptionShape,
    type Point,
    type RgbColor,
    type FillStyle,
    type StrokeStyle,
    type CaptionBackgroundStyle,
    type CaptionPointerConfig,
    type CaptionThoughtConfig,
    type CaptionConfigInput,
    type CaptionConfig,
    type CaptionState,
} from './types';
export {
    computePointerTriangle,
    getRectBoundaryPoint,
    getEllipseBoundaryPoint,
    getThoughtScallops,
    triangleToPathPoints,
    type TrianglePoints,
    type ThoughtScallop,
} from './geometry';
